root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ."
post_cmd = [] 
pre_cmd = []
delay = 0
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "templ"]
include_file = []
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = true
follow_symlink = false
full_bin = ""
kill_delay = "0s"  
log = "build-errors.log"
poll = false
poll_interval = 0
rerun = true
rerun_delay = 0
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = true

[misc]
clean_on_exit = true

[proxy]
app_port = 8080
enabled = true
proxy_port = 3000

[screen]
keep_scroll = true
